name: Make Repo Public

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Check date and change visibility
        run: |
          TARGET_DATE=1685874600
          CURRENT_DATE=$(date +%s)

          if [ $CURRENT_DATE -ge $TARGET_DATE ]; then
            RESPONSE=$(curl \
              -s \
              -o /dev/null \
              -w "%{http_code}" \
              -X PATCH \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }} \
              -d '{"visibility":"public"}')

            if [ $RESPONSE -eq 200 ]; then
              echo "Repository visibility successfully changed to public."
            else
              echo "Failed to change repository visibility. HTTP response code: $RESPONSE"
              exit 1
            fi
          else
            echo "Current date is not yet the target date. Skipping."
          fi
